### ISSUE TITLE
Still mostly Go?

### ISSUE THREAD

**Issue by jdrews** [zerotier/lf#1]
https://github.com/zerotier/lf#building-and-running
>  It's mostly written in Go (1.11+ required) with some C for performance critical bits.

![image](https://user-images.githubusercontent.com/172766/59560133-ad9e8380-8fda-11e9-93b6-d40afdc17e8c.png)

On another note: This looks really neat! Excited to see where this goes.

**Comment by glimberg** [comment]
Most of that C is from https://github.com/zerotier/lf/tree/master/native/sqlite3.  We included that in the source tree because some Linux distros only have ancient packages available (I'm looking at you CentOS)
