### ISSUE TITLE
FYI - EdgeFS, scale-out, multi-cloud scalable S3/NFS/iSCSI distributed storage system for Edge/IoT Computing

### ISSUE THREAD

**Issue by sbilly** [zerotier/lf#11]
FYI - EdgeFS, scale-out, multi-cloud scalable S3/NFS/iSCSI distributed storage system for Edge/IoT Computing

https://github.com/Nexenta/edgefs

![-w600](https://github.com/Nexenta/edge-dev/raw/master/images/edgefs-multicloud.png?raw=true)

EdgeFS is capable of spanning unlimited number of geographically distributed sites (Geo-site), connected with each other as one global name space data fabric running on top of Kubernetes platform, providing persistent, fault-tolerant and high-performance fully compatible S3 Object API and CSI volumes for stateful Kubernetes Applications.

At each Geo-site, EdgeFS segment nodes deployed as containers (Kubernetes StatefulSet or Docker Compose) on physical or virtual nodes, pooling available storage capacity and presenting it via compatible S3/NFS/iSCSI/etc storage emulated protocols for cloud-native applications running on the same or dedicated servers.

**Comment by adamierymenko** [comment]
Could be useful in clusters but isn't secure across trust boundaries.

**Comment by sbilly** [comment]
IPFS can secure across trust boundaries, and acting as a filesystem.
