### ISSUE TITLE
Using LF in a private network architecture deployment

### ISSUE THREAD

**Issue by mckenziec** [zerotier/lf#12]
Hi. Really excited to start playing with LF. I've been looking for a decentralized KV replication framework for a long time. I'm hoping you've nailed it. 👍  

I'm looking to run KV replication between multiple servers to share some basic configuration data (without the limitations of distributed hashing or centralized approaches) but the private network instructions included in this project are a bit to basic.

So far I've gotten this far:

```
$ mkdir ~/lf_data
$ lf makegenesis
$ lf -path /home/user/lf_data/ -json node-start
```

Then in another term (note these are test keys/certs):

```
$ ls -path /home/user/lf_data status
{
  "Software": "ZeroTier LF Reference",
  "Version": [0, 9, 24, 0],
  "APIVersion": 1,
  "MinAPIVersion": 1,
  "MaxAPIVersion": 1,
  "Uptime": 254,
  "Clock": 1566569903,
  "RecordCount": 2,
  "DataSize": 1286,
  "FullySynchronized": true,
  "GenesisRecords": "\bHaRsnbEKxzWOIWIwSi5J14B06EqWCRRRNvDLHAxfXn9wNvZkxbGa3E7ggRyBS8U0i8gmiaD7BmDIrpXa4g69DNvJAcr9VkhKpG1hB1WeWGVPxj2AGD0Y30EIQ48b0pNBiX5t6SeiJXbjpdSm31ahqme9xv97s1KTjnL2CQVGiNzTzNU6wV53FdA42dt69agXBcb83v6la4pQVCz8hPXMadV78hdxJPG3lI0cKbSuMkD4P2F8Azujxvpnm8slv2rwCEtTNyUMUsActlfSljfkToFqGIwo2bmLu7GdavflSyqZNaLwQUNrXmyQCKIVBeahJE09HEZRgFPrWxySr4yV2IfXO8ROcQfDtGdDB6CSq9TuuslGtzmV7GT57kVbyXB8bMIAMGJogYLnn4h1CRl3FNJLsxW5cR1ESF52bIAuXSJTe1mymKy1bYx7t7pWB5jM4I7Qx6g8V2VbxBW4E0cQxVUKisQ2qM9LNTvKugHfrLlyEEfturhcpdwdZb2yPWC7M93R09CI5QmwFl6x8Vefn6krLuFNLOqOgzzkzIwhgvOIRg3zKIvR6Zf9tXizcL6YdXwqPABGVMQM2zATDORr4BIueujZWziWTm2u6PrvRcqfzqsqgETT3kUxHoJqdgmuCvQdX6fQj2MSeFFGrnpmov4OGEfM7AyrZmA2BIVH6wIx1jJqPGosRqeNUdnL2Bz2kdbLuGXXH3UrJEQKfZYUSXzo9ZPQhEto871sdicwJdDiBNGSPEAZllYso6ZIryGxq5fZIBfpLLYad35085I5knvn7iwLl1tpIpmty7uMaBG24RJReEO9DfDKbtg483Y3pHTWamC0uXcEXz8QDp2bIbZ171AHCxhJmFvS1TzjkmAotLXDlfurtmDbv4mtxAONkm2pT8jHbqgI20rO8HvrO5aUXWEd1m9WTo9w5IgZ698YGTwXcWqmvLPbGquhcyU40t9KRGzj2ZHfyK8GqWL3zhswnDY8Z91aDwMklPCWVnRPos670MgY0E5wKawWoakJwFLVZrZd2mvDM1aB3rzNgkXz9cFnBslWTOzvCj04HdAuFxDTdAH0foCIkkz20ByaansGOjxcWQseMrarHWh78BXk6jQrTydbv2KBiqPhX3vkRlQSa3foozyMXVhygIpD3ln4XQ3S67vMhieyAtMYgGE9DQDWLBOrNTXPAd9KQDjF9GRM3tBMy4QsKSB1NfOCMNKiH1N1SuTpkXiCaMhmIjjkLVwVX3J1FwKemohqDbNnxvTlygTFB05bOoXeScXZNV4rrlwKNTMDygwKreZmA0AeHaxGFehtHmhN71gkbb7VARnaV0FZvWkjPkNmAMDlyklGJNI5fn8JpgIEbE8QBgmoRw5MJcTJJ9rMheYWkJacXYOj31JW58reUrZCQpwSWbpSXRzQ7SRc83DFC42qEQzKf6QAyCvo0bjPcVbdz7snV47YxSZIFtTPZNm6yHzxKPi78H3ndp5hACciNH9Jt51TafwbQh9d1JWifwTyRQ12OhZugufarZ7oPetR3zsQrBQl2eXvWRlY011aXrMYWjVvRCUs3SclW3M3cxd3cNencVNr25vYTKSa9nkNXI5WVsq6hzCvI8Nu0dcrt4PF6nZZz8oH81iA2Q2nM8VvBBWY1qxYL3hPbmpxYY4Dyf0HebXKvljfBNGN3ra70TxBeyNOSnMPIfKvUia16gIte6mzvS63xX1VSqkGz5X64bLF",
  "GenesisParameters": {
    "ID": [153, 53, 94, 241, 154, 32, 192, 98, 227, 92, 205, 131, 213, 7, 66, 102, 96, 158, 12, 138, 84, 27, 67, 103, 227, 228, 163, 134, 106, 95, 57, 195],
    "AmendableFields": ["authcertificates"],
    "Name": "unity",
    "Contact": "etcd1@test.com",
    "AuthCertificates": "\bidKH8qMHjgeh4pfSaC7wSlwZS6oq40lp5pTT2rwGvPzkCdetlF0Z8oMwR8ijL36jyQO74VhcpEUJlksVWOlLImAeb1Xf5ZZvK451x7gVNakSzkfopX7pLlt7SqfDk2QIbY3HUnMDSSaj21mMiAqVk6fGzdDtuANTDp9A3hDGv7TCTzelX5JgMmmimOX6xDjotHr7M0Q7I1lOvprNVBkYkxm9gg4KzhjqG30X8iooBtCGXwTCx72zfRRw5YcW1onMVPektGysG0XKTQlLpyCxdLIcnHCjIGWNTMSt8P0bUjznExR9V2yKyeff8pRw4DEWVktgLAqZxt0ja14ozmPVi9HnTPS3IJ2HYfSHgiixepd0W3IZxEahgLLyKaB7dvlbtV0ceNpJjy9FmokwVau3IRYcGHNxGeXgeGOnG5dGP9SRzQJEXKBhPztT51JHjfaY9VzHVNM942sPpOFRuwQcoh8sK7vLbRQtFd2NJLznAy0QmJs9OxzQQsPOOJmtKNbfehd3XG5xAi6ITQdyDZ6j7LWcVltPbykrd2L5GzadaDGckQI3RGPmkN7MsH5M6d12LbwuyeCHlzk1vYmRpcIbLidyuxbOJ5upXsiLJavnrzMskm4ajOAWD1yYOQHzLCGTQf39SEXGDVRgO7vCyMJzusYgbD4sCYWlALWpcFYrZyV1kvVgXqbISqp2X846fd1xBPfj3wcqPAIUA4zUeeBpKqvunrTdZQf7FUcQVwIuU2D6Dw2JXg61ZSQvM7HwFDMM9I6VOHrm1AXOZiruAjZJdYVx2f6cN2Ay2QOl26mI9WZYUO6aKAX43ZtOC5RqbyljLF9wy1q1fPOM7R5leaX4eadtKS2SR2bQ3Y2Wz38wPJd3IMMh7FYItmhghjstIixTWcQNWGWHXldeu0fBJxxgtPqTWTOOS0jEpZ6V9eAY9P1DyV3L3LFhWifJJboBZ8L",
    "AuthRequired": false,
    "RecordMinLinks": 2,
    "RecordMaxValueSize": 1024,
    "RecordMaxTimeDrift": 60
  },
  "P2PPort": 9908,
  "LocalTestMode": false,
  "Identity": "\bLfCyQ09gydhx9ASP7UsqEqWSY8ajvMfOs3XN9vjpBgjiGqjuMZwX2KfjREaXSHkPV"
}
```

What's next? How do I setup and peer another node correctly? Do I copy some of the genesis files over to other nodes? Or some lf usage? Is the owner command part of the equation? If so, when making a genesis db, where and how is the CA key/cert part of it?

Also, for the private network and cert generation, what key parts of the form should be linked to the network/server?

Can makegenesis be automated? e.g. pass in the form values up front so it's not necessary to re-type during testing, etc...

Thanks and I'm looking forward to testing lf!

**Comment by adamierymenko** [comment]
Awesome! You are almost there.

LF is *sort of* like a block chain (only it's a tree, not a list, and it's not a coin). What you've done is create "genesis blocks" that contain the configuration of your network and its certificates.

For other nodes that you create you will want to copy `genesis.lf` into `/var/lib/lf` or `~/.lf` (depending on whether you are running as root or a user) to the other nodes **before** firing them up. If that file doesn't exist, LF uses the compiled-in "Sol" defaults.

After your other nodes are up you will need to `lf node-connect` them to each other. You only have to connect to one node. After that it'll find the others. The connectivity graph is arbitrary and replication will happen as long as one link somewhere is up. Once you connect once you shouldn't need to do it again unless you move everything.

If you want to run LF at the edge and you're behind NATs, etc., just run it over ZeroTier. :)

It looks like your network is not `AuthRequired`, meaning you can do proof of work to add records. If you `lf owner authorize` you can exempt owners from the PoW requirement. This is done by making a CRL for the owner and then authorizing it. It's similar to getting SSL certs signed.

**Comment by adamierymenko** [comment]
BTW the license on this is changing to the BSL 1.1 like ZeroTier itself. It shouldn't affect what you're doing. It'll be almost identical to CockroachDB's license.

**Comment by sbilly** [comment]
hi, @mckenziec 

Did you deploy lf successfully? Could you please to write a deployment guide?
