### ISSUE TITLE
Webtorrent, IPFS, LibP2P could benefit from this project if it were available for Node.js

### ISSUE THREAD

**Issue by draeder** [zerotier/lf#19]
I read through the readme and I'm fascinated by this project. I've been interested in decentralization for a long time. One of the biggest problems facing web-based decentralization is the need for centralized signaling servers to allow browsers to speak with each other directly over WebRTC. LF has serious potential to solve that problem.

Given the speed of puts and gets on LF, and the way data for a topic is chained, LF could potentially serve as a fully distributed WebRTC signaling server to connect peers together without the need for centralized signaling servers. That is a truly powerful prospect.

@feross
@mafintosh
@DiegoRBaquero

**Comment by adamierymenko** [comment]
You could easily access the API via NodeJS. Porting to NodeJS would be a big task.

BTW we have relicensed this as MPL-2.0
