### ISSUE TITLE
Whenever there's a concept called seed node, GreatFirewall licks

### ISSUE THREAD

**Issue by immartian** [zerotier/lf#2]
For a fully decentralized system, blockchain is not a referential model as it proved not censorship-resistant in China. The Great Firewall(GFW) system can easily block those seed nodes and/or sniff further variations like Tor was totally crippled there. 

https://github.com/zerotier/lf/blob/ad6510647ab777f17109f9c0bc6d2c9ec4c1b42a/pkg/lf/defaults.go#L51

What's the real unblockable model? It's worth of debate in depth.

**Comment by adamierymenko** [comment]
The seed nodes here are just suggestions. LF is fully replicated so any node can be a seed node. All nodes are the same.

**Comment by adamierymenko** [comment]
Also note that evading the GFW is not a primary goal of this system, so it's a bit out of scope. If the GFW can block this categorically it would have to be run over some kind of network overlay, tunnel, VPN, etc.

**Comment by adamierymenko** [comment]
One more point on the GFW: LF's connectivity graph is arbitrary since all nodes have and replicate the same data. So if there are one or two working LF links in/out of China the nodes within China can connect to each other and the GFW will not matter.
