### ISSUE TITLE
Is this project and the public service dead?

### ISSUE THREAD

**Issue by eici** [zerotier/lf#20]
➜  lf git:(master) ./lf status
ERROR: status query failed: Get "https://lf.zerotier.com/status": dial tcp 50.7.73.34:443: connect: connection refused

**Comment by adamierymenko** [comment]
Project is technically not dead, but the public service definitely needs a reboot! fixing...

**Comment by adamierymenko** [comment]
Project is useful and usable as-is but will probably get an update before it's used in ZT in any public facing role. We have some air gapped uses.

**Comment by adamierymenko** [comment]
There have not been updates recently because... it works, and we're busy, and it works.

**Comment by eici** [comment]
Hi @adamierymenko thanks for responding! I really like the idea behind lf, so i'm glad it will see more love ;-)

Anyway, when using the public service i still get:

➜  lf git:(master) ./lf status
ERROR: status query failed: Get "https://lf.zerotier.com/status": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by adamierymenko** [comment]
The public service should exist again. However the future of this project is uncertain. We relicensed it recently under MPL-2.0 since if it doesn't end up being deployed widely in its current state its code or ideas will be useful to others. In any case, it works.
