### ISSUE TITLE
Incentives to run nodes?

### ISSUE THREAD

**Issue by asbjornenge** [zerotier/lf#4]
Hi there!

Super cool project and great solution to decentralize ZeroTier (and lots of other things) 💖 🚀  I wonder about incentives for users to host a lf node to increase decentralization. Are they simply supposed to see the intrinsic value of doing this? Seems some incentive solution would drive decentralization much further 🤔

Also, are you looking for people to host lf nodes and join `lf.zerotier.com` as a peer?

Regards,
Asbjorn

**Comment by adamierymenko** [comment]
The incentive would be performance and infrastructure independence, same as running your own ZeroTier roots. I don't think it matters if there are a ton of LF nodes or not as they all cache the same data.

Also the seed nodes like lf.zerotier.com are just suggestions to make things "zero configuration." It doesn't matter which nodes are initially contacted unless you suspect some of them might be bad actors.

**Comment by adamierymenko** [comment]
What we are looking for is people to bang on this, find bugs, and suggest features. :)

**Comment by asbjornenge** [comment]
Infrastructure independence might do the trick for many 👍 Thanks for the reply 😄 I'll look into running a node when I find some time 😄
