### ISSUE TITLE
how to keep lf network private ?

### ISSUE THREAD

**Issue by sbilly** [zerotier/lf#6]
Private ZeroTier network requires private LF, and private LF network requires ZeroTier. I'm wondering  how to keep both LF and ZeroTier private ?

According to [README.md](https://github.com/zerotier/lf/blob/master/README.md):

```
LF peers will not talk to one another if they aren't members of the same network. This is accomplished by cryptographic means using the network's unique 256-bit ID as a pre-shared key. Beyond this simple mechanism there is no system built into LF to control node access over the network. It's the responsibility of those running private networks to secure them by (for example) running them only over ZeroTier virtual networks instead of over the public Internet.
```

Private ZeroTier network needs a working root which need LF.
Private LF network need ZeroTier to protect it from public internet.

???

**Comment by adamierymenko** [comment]
You can create private LF networks, but there's no relationship between that and privater ZeroTier networks. The whole idea of LF is that multiple tenants can share the same network/database safely and securely.

**Comment by sbilly** [comment]
ZeroTier root can use lf to sync network/database safely and securely. But any malicious lf node can join this lf network if it has the pre-shared unique 256-bit ID. How can I protect it with my private ZeroTier network?

![image](https://user-images.githubusercontent.com/123563/60958160-7cdf0f00-a338-11e9-9527-7a48b1318484.png)


According to  [README.md#L320](https://github.com/zerotier/lf/blame/master/README.md#L320)

**Comment by janjaapbos** [comment]
If you have a private ZT network, then you can activate that network on the lf nodes, and restrict lf to only bind to the address of that private ZT network. Or use iptables / firewall to only allow lf traffic over the private ZT network. 

That private ZT network could e.g. hosted at my.zerotier.com, in order to prevent chicken / egg issues.

**Comment by sbilly** [comment]
Thank you @janjaapbos 

I've thought about using firewall (e.g. iptables) to block LF traffic from unknown nodes. If using firewall,  I will have to re-configure all firewalls on every LF nodes to add/remove LF node. I think it is not an elegant way for a p2p system.

And if LF and ZT are working in an air-gapped network and nobody can reach my.zerotier.com, that will be a chicken / egg issue.


ps: I think ZT and LF are both elegant P2P systems.
ps2: lol for 'chicken / egg issue'.  😄

**Comment by adamierymenko** [comment]
The whole point of LF is to not have to block traffic from unknown nodes. It doesn't matter where a record comes from. Everything is cryptographically authenticated.

If you want to run a private network with a private config on the public Internet you could do that I suppose.
